-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 00:45:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema creche
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema creche
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creche` DEFAULT CHARACTER SET utf8 ;
USE `creche` ;

-- -----------------------------------------------------
-- Table `creche`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Pessoa` (
  `cartaoCidadao` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cartaoCidadao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Turma` (
  `idTurma` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idTurma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`Educador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Educador` (
  `idEducador` INT NOT NULL AUTO_INCREMENT,
  `contacto` INT UNSIGNED NOT NULL,
  `salario` FLOAT UNSIGNED NOT NULL,
  `Turma_idTurma` INT UNSIGNED NOT NULL,
  `Pessoa_cartaoCidadao` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `contacto_UNIQUE` (`contacto` ASC) VISIBLE,
  PRIMARY KEY (`idEducador`, `Turma_idTurma`, `Pessoa_cartaoCidadao`),
  INDEX `fk_Educador_Turma1_idx` (`Turma_idTurma` ASC) VISIBLE,
  INDEX `fk_Educador_Pessoa1_idx` (`Pessoa_cartaoCidadao` ASC) VISIBLE,
  CONSTRAINT `fk_Educador_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `creche`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Educador_Pessoa1`
    FOREIGN KEY (`Pessoa_cartaoCidadao`)
    REFERENCES `creche`.`Pessoa` (`cartaoCidadao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`Crianca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Crianca` (
  `idCrianca` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_cartaoCidadao` INT NOT NULL,
  `Pessoa_cartaoCidadao1` INT UNSIGNED NOT NULL,
  `Turma_idTurma` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `Pessoa_cartaoCidadao_UNIQUE` (`Pessoa_cartaoCidadao` ASC) VISIBLE,
  PRIMARY KEY (`idCrianca`, `Pessoa_cartaoCidadao1`, `Turma_idTurma`),
  INDEX `fk_Crianca_Pessoa1_idx` (`Pessoa_cartaoCidadao1` ASC) VISIBLE,
  INDEX `fk_Crianca_Turma1_idx` (`Turma_idTurma` ASC) VISIBLE,
  CONSTRAINT `fk_Crianca_Pessoa1`
    FOREIGN KEY (`Pessoa_cartaoCidadao1`)
    REFERENCES `creche`.`Pessoa` (`cartaoCidadao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crianca_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `creche`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`Atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Atividade` (
  `idAtividade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `duracao` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `objetivo` VARCHAR(45) NOT NULL,
  `Educador_idEducador` INT NOT NULL,
  `Educador_Turma_idTurma` INT UNSIGNED NOT NULL,
  `Educador_Pessoa_cartaoCidadao` INT UNSIGNED NOT NULL,
  `Turma_idTurma` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAtividade`, `Educador_idEducador`, `Educador_Turma_idTurma`, `Educador_Pessoa_cartaoCidadao`, `Turma_idTurma`),
  UNIQUE INDEX `idAtividade_UNIQUE` (`idAtividade` ASC) VISIBLE,
  INDEX `fk_Atividade_Educador1_idx` (`Educador_idEducador` ASC, `Educador_Turma_idTurma` ASC, `Educador_Pessoa_cartaoCidadao` ASC) VISIBLE,
  INDEX `fk_Atividade_Turma1_idx` (`Turma_idTurma` ASC) VISIBLE,
  CONSTRAINT `fk_Atividade_Educador1`
    FOREIGN KEY (`Educador_idEducador` , `Educador_Turma_idTurma` , `Educador_Pessoa_cartaoCidadao`)
    REFERENCES `creche`.`Educador` (`idEducador` , `Turma_idTurma` , `Pessoa_cartaoCidadao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atividade_Turma1`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `creche`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`Avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `nota` VARCHAR(45) NOT NULL,
  `observacao` VARCHAR(45) NULL,
  `data` DATETIME NOT NULL,
  `Crianca_idCrianca` INT NOT NULL,
  `Atividade_idAtividade` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAvaliacao`, `Crianca_idCrianca`, `Atividade_idAtividade`),
  INDEX `fk_Avaliacao_Crianca1_idx` (`Crianca_idCrianca` ASC) VISIBLE,
  INDEX `fk_Avaliacao_Atividade1_idx` (`Atividade_idAtividade` ASC) VISIBLE,
  CONSTRAINT `fk_Avaliacao_Crianca1`
    FOREIGN KEY (`Crianca_idCrianca`)
    REFERENCES `creche`.`Crianca` (`idCrianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Avaliacao_Atividade1`
    FOREIGN KEY (`Atividade_idAtividade`)
    REFERENCES `creche`.`Atividade` (`idAtividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`EncarregadoEducacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`EncarregadoEducacao` (
  `idEncarregado` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_cartaoCidadao` INT UNSIGNED NOT NULL,
  `contacto` VARCHAR(45) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `Pessoa_cartaoCidadao1` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEncarregado`, `Pessoa_cartaoCidadao1`),
  INDEX `fk_EncarregadoEducacao_Pessoa1_idx` (`Pessoa_cartaoCidadao1` ASC) VISIBLE,
  CONSTRAINT `fk_EncarregadoEducacao_Pessoa1`
    FOREIGN KEY (`Pessoa_cartaoCidadao1`)
    REFERENCES `creche`.`Pessoa` (`cartaoCidadao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`AuxiliarEducativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`AuxiliarEducativo` (
  `idAuxiliar` INT NOT NULL AUTO_INCREMENT,
  `funcao` VARCHAR(45) NOT NULL,
  `salario` FLOAT NOT NULL,
  `Pessoa_cartaoCidadao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAuxiliar`, `Pessoa_cartaoCidadao`),
  INDEX `fk_AuxiliarEducativo_Pessoa1_idx` (`Pessoa_cartaoCidadao` ASC) VISIBLE,
  CONSTRAINT `fk_AuxiliarEducativo_Pessoa1`
    FOREIGN KEY (`Pessoa_cartaoCidadao`)
    REFERENCES `creche`.`Pessoa` (`cartaoCidadao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_cartaoCidadao` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAdministrador`, `Pessoa_cartaoCidadao`),
  INDEX `fk_Administrador_Pessoa1_idx` (`Pessoa_cartaoCidadao` ASC) VISIBLE,
  CONSTRAINT `fk_Administrador_Pessoa1`
    FOREIGN KEY (`Pessoa_cartaoCidadao`)
    REFERENCES `creche`.`Pessoa` (`cartaoCidadao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`Crianca_has_EncarregadoEducacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Crianca_has_EncarregadoEducacao` (
  `Crianca_idCrianca` INT NOT NULL,
  `EncarregadoEducacao_idEncarregado` INT NOT NULL,
  PRIMARY KEY (`Crianca_idCrianca`, `EncarregadoEducacao_idEncarregado`),
  INDEX `fk_Crianca_has_EncarregadoEducacao_EncarregadoEducacao1_idx` (`EncarregadoEducacao_idEncarregado` ASC) VISIBLE,
  INDEX `fk_Crianca_has_EncarregadoEducacao_Crianca1_idx` (`Crianca_idCrianca` ASC) VISIBLE,
  CONSTRAINT `fk_Crianca_has_EncarregadoEducacao_Crianca1`
    FOREIGN KEY (`Crianca_idCrianca`)
    REFERENCES `creche`.`Crianca` (`idCrianca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crianca_has_EncarregadoEducacao_EncarregadoEducacao1`
    FOREIGN KEY (`EncarregadoEducacao_idEncarregado`)
    REFERENCES `creche`.`EncarregadoEducacao` (`idEncarregado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creche`.`Anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creche`.`Anuncio` (
  `idAnuncio` INT NOT NULL AUTO_INCREMENT,
  `Administrador_idAdministrador` INT NOT NULL,
  `Administrador_Pessoa_cartaoCidadao` INT UNSIGNED NOT NULL,
  `descricao` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`idAnuncio`, `Administrador_idAdministrador`, `Administrador_Pessoa_cartaoCidadao`),
  UNIQUE INDEX `idAnuncios_UNIQUE` (`idAnuncio` ASC) VISIBLE,
  INDEX `fk_Anuncios_Administrador1_idx` (`Administrador_idAdministrador` ASC, `Administrador_Pessoa_cartaoCidadao` ASC) VISIBLE,
  CONSTRAINT `fk_Anuncios_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador` , `Administrador_Pessoa_cartaoCidadao`)
    REFERENCES `creche`.`Administrador` (`idAdministrador` , `Pessoa_cartaoCidadao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
